// src/app/components/likeButton.tsx
'use client'

import { FC, useState } from 'react'

export const LikeButton: FC<{ className?: string }> = ({ className = '' }) => {
  const [likeCount, setLikeCount] = useState(0)

  function handleClick() {
    setLikeCount(likeCount + 1)
  }

  return (
    <button onClick={handleClick} className={`btn ${className}`}>
      Like ({likeCount})
    </button>
  )
}

// ui/src/components/LikeButton.svelte
<script lang="ts">
	import { debounce } from '$lib/utils/debounce'
	import { createEventDispatcher } from 'svelte'

	export let likeCount = 0

	const dispatch = createEventDispatcher<{ like: { count: number } }>()

	const onLike = debounce(() => {
		likeCount++
		dispatch('like', { count: likeCount })
	}, 200)
</script>

<button on:click={onLike} class="btn">Like ({likeCount})</button>
