// ui/src/components/toast/Toast.svelte
<script lang="ts">
	import type { ToastLevel } from '$lib/model/toast'
	import { deleteToast } from '$lib/toast/action'
	import { PausableTimer } from '$lib/utils/timer'
	import { onMount } from 'svelte'
	import { tweened } from 'svelte/motion'

	export let id: number
	export let message: string
	export let level: ToastLevel

	const timeout = 10_000

	const progress = tweened(0, { duration: timeout })
	let timer: PausableTimer
	let lastStop = 0

	onMount(() => {
		progress.set(1)

		timer = new PausableTimer(() => {
			deleteToast(id)
		}, timeout)
	})

	function pauseProgress() {
		timer.pause()
		lastStop = $progress
		progress.set(lastStop, { duration: 0 })
	}

	function resumeProgress() {
		timer.resume()
		progress.set(1, { duration: (1 - lastStop) * timeout })
	}
</script>

<div
	role="alertdialog"
	on:mouseenter={pauseProgress}
	on:mouseleave={resumeProgress}
	class="alert mask relative block overflow-hidden text-left"
	class:alert-info={level === 'info'}
	class:alert-success={level === 'success'}
	class:alert-warning={level === 'warning'}
	class:alert-error={level === 'error'}
>
	<button
		on:click={() => deleteToast(id)}
		class="btn-ghost btn-sm btn-circle btn absolute right-2 top-3">✕</button
	>
	<div class="whitespace-pre-line break-words pr-6">{message}</div>
	<div class="absolute bottom-0 left-0 w-full bg-transparent">
		<div
			class="h-1 rounded-full"
			class:bg-info-content={level === 'info'}
			class:bg-success-content={level === 'success'}
			class:bg-warning-content={level === 'warning'}
			class:bg-error-content={level === 'error'}
			style={`width: ${(1 - $progress) * 100}%`}
		/>
	</div>
</div>

// ui/src/components/toast.tsx
'use client'

import { animated, useSpring } from '@react-spring/web'
import React, { FC, useEffect, useRef } from 'react'
import { Toast } from '@/lib/model/toast'
import { useAppDispatch, useAppSelector } from '@/lib/redux/hooks'
import { deleteToast } from '@/lib/redux/toast/thunk'
import { Timer } from '@/lib/utils/timer'

export const ToastContainer: FC = () => {
  const toasts = useAppSelector((state) => state.toast.toasts)

  return (
    <div className="toast-center toast w-full min-w-0 sm:w-[500px]">
      {toasts.map((toast) => (
        <ToastItem key={toast.id} {...toast} />
      ))}
    </div>
  )
}

export const ToastItem: FC<Toast> = ({ id, message, level }) => {
  const deleteTimeout = 10_000

  const dispatch = useAppDispatch()
  const timer = useRef<Timer>()

  useEffect(() => {
    timer.current = new Timer(() => {
      dispatch(deleteToast({ id, deleteAfter: 0 }))
    }, deleteTimeout)
  }, [id, dispatch])

  const [progressSpring, progressApi] = useSpring(() => {
    return {
      from: {
        width: '100%',
      },
      to: {
        width: '0%',
      },
      config: {
        duration: deleteTimeout,
      },
    }
  })

  const pauseTimer = () => {
    timer.current?.pause()
    progressApi.pause()
  }

  const resumeTimer = () => {
    timer.current?.resume()
    progressApi.resume()
  }

  return (
    <div
      onMouseEnter={pauseTimer}
      onMouseLeave={resumeTimer}
      className={`alert mask relative block overflow-hidden alert-${level}`}
    >
      <button
        onClick={() => dispatch(deleteToast({ id, deleteAfter: 0 }))}
        className="btn-ghost btn-sm btn-circle btn absolute right-2 top-3"
      >
        ✕
      </button>
      <div className="whitespace-pre-line break-words pr-6">{message}</div>
      <div className="absolute bottom-0 left-0 w-full bg-transparent">
        <animated.div
          className={`h-1 rounded-full bg-${level}-content`}
          style={progressSpring}
        ></animated.div>
      </div>
    </div>
  )
}
