// ui/src/components/text/LabeledText.svelte
<script lang="ts">
	export { clazz as class }
	let clazz: string = ''

	export let label: string
	export let value: string
	export let isCode: boolean = false
</script>

<div class={clazz}>
	<span class="ml-2 text-xs font-light">{label}</span>
	<div class="border-base-200 border-t">
		<span class="ml-2" class:font-mono={isCode}>{value}</span>
	</div>
</div>

// ui/src/components/form/labeledText.tsx
import { FC } from 'react'

export const LabeledText: FC<{
  label: string
  value: string
  isCode?: boolean
  className?: string
}> = ({ label, value, isCode = false, className = '' }) => {
  return (
    <div className={className}>
      <label className="ml-2 text-xs font-light">{label}</label>
      <div className="border-t border-base-200">
        <span className={`ml-2 ${isCode ? 'font-mono' : ''}`}>{value}</span>
      </div>
    </div>
  )
}
